name: dockerpull

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image
        run: |
          IMAGE_NAME="cryptax/android-re:2024.02"
          echo "Pulling Docker image..."
          docker pull $IMAGE_NAME

      - name: Run Docker container
        run: |
          CONTAINER_NAME="android-retools"
          IMAGE_NAME="cryptax/android-re:2024.02"
          echo "Running Docker container..."
          cat <<EOL > docker-compose.yml
          version: '3.7'
          services:
            $CONTAINER_NAME:
              image: $IMAGE_NAME
              container_name: $CONTAINER_NAME
          EOL
          docker-compose up -d

      - name: Get container ID
        id: container_id
        run: |
          CONTAINER_NAME="android-retools"
          CONTAINER_ID=$(docker ps -qf "name=$CONTAINER_NAME")
          echo "::set-output name=id::$CONTAINER_ID"

      - name: Export container filesystem
        run: |
          CONTAINER_ID=${{ steps.container_id.outputs.id }}
          TAR_NAME="android-retools.tar"
          if [ -z "$CONTAINER_ID" ]; then
            echo "Failed to start the Docker container."
            exit 1
          fi
          echo "Container ID: $CONTAINER_ID"
          echo "Exporting container filesystem to tarball..."
          docker export $CONTAINER_ID -o $TAR_NAME

      - name: Compress the tarball
        run: |
          TAR_NAME="android-retools.tar"
          COMPRESSED_TAR_NAME="android-retools.tar.gz"
          echo "Compressing the tarball..."
          tar -czvf $COMPRESSED_TAR_NAME $TAR_NAME

      - name: Clean up
        run: |
          TAR_NAME="android-retools.tar"
          echo "Cleaning up..."
          rm $TAR_NAME

      - name: Upload compressed tarball
        uses: actions/upload-artifact@v3
        with:
          name: compressed-tarball
          path: android-retools.tar.gz
