name: Run JavaScript

on:
  workflow_dispatch:

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Execute JavaScript code
        run: |
          node itrchk.js
